# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACLearn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
 pod 'ReactiveCocoa', '~> 2.5'
  # Pods for RACLearn

  target 'RACLearnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACLearnUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
